name: template-qt-snap
version: "0.0.1"
summary: a template for basic qt snap
description: |
 a template for basic qt snap

confinement: strict
base: core20

apps:
  my-application:
    common-id: qt-demo.desktop
    command: usr/bin/my_application
    extensions:
      - kde-neon
    plugs:
      - home
      - opengl
      - network
      - network-bind
      - pulseaudio

slots:
  session-dbus-interface:
    interface: dbus
    name: qt-demo.desktop
    bus: session

parts:
  my-application:
    build-snaps:
      - kde-frameworks-5-qt-5-15-3-core20-sdk
      - kde-frameworks-5-qt-5-15-3-core20
    plugin: cmake
    build-packages:
      - qt5-default
#    stage-packages:
#      - #put your runtime dependencies here
    source-type: local
    source: .
    cmake-parameters:
      - "-DCMAKE_INSTALL_PREFIX=/usr"

